/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdvogadosRouteImport } from './routes/advogados'
import { Route as IndexRouteImport } from './routes/index'

const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadosRoute = AdvogadosRouteImport.update({
  id: '/advogados',
  path: '/advogados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advogados': typeof AdvogadosRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advogados': typeof AdvogadosRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advogados': typeof AdvogadosRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advogados' | '/blog' | '/contato'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advogados' | '/blog' | '/contato'
  id: '__root__' | '/' | '/advogados' | '/blog' | '/contato'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvogadosRoute: typeof AdvogadosRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogados': {
      id: '/advogados'
      path: '/advogados'
      fullPath: '/advogados'
      preLoaderRoute: typeof AdvogadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvogadosRoute: AdvogadosRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
